dist: jammy
language: c
env:
#- PG_MAJOR=19
#- PG_MAJOR=18
- PG_MAJOR=17
#- PG_MAJOR=16
#- PG_MAJOR=15
#- PG_MAJOR=14
#- PG_MAJOR=13
before_script:
- sudo apt-get -y purge postgresql-client-common
#- sudo rm /etc/apt/sources.list.d/postgresql.list
#- sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -p
#- sudo apt-get install -y postgresql-common
#- sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -p -i -v ${PG_MAJOR}
#- sudo systemctl stop postgresql
#script: ./run-tests.sh
script: /usr/bin/true
#after_script:
#- cat regression.diffs
#- cat logfile
