dist: jammy
language: c
env:
- PG_MAJOR=19
- PG_MAJOR=18
- PG_MAJOR=17
- PG_MAJOR=16
- PG_MAJOR=15
- PG_MAJOR=14
- PG_MAJOR=13
before_script:
- sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -y
- sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -p -i -v ${PG_MAJOR}
- sudo systemctl stop postgresql
script: ./run-tests.sh
after_script:
- cat regression.diffs
- cat logfile
